In [1]:
import pandas as pd

In [2]:
data = {
    "hours_studied" : [1,2,3,4,5,6,7,8,9,10],
    "passed" : [0,0,0,0,0,1,1,1,1,1]
}

In [3]:
df = pd.DataFrame(data)
df

   hours_studied  passed
0              1       0
1              2       0
2              3       0
3              4       0
4              5       0
5              6       1
6              7       1
7              8       1
8              9       1
9             10       1

In [11]:
X = df[["hours_studied"]]
y = df["passed"]

In [12]:
X

   hours_studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

In [13]:
y

0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    1
8    1
9    1
Name: passed, dtype: int64

In [14]:
import sklearn

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [17]:
print(X_train)

   hours_studied
5              6
0              1
7              8
2              3
9             10
4              5
3              4
6              7

In [12]:
print(X_test)

   hours_studied
8              9
1              2

In [13]:
print(y_train)

5    1
0    0
7    1
2    0
9    1
4    0
3    0
6    1
Name: passed, dtype: int64

In [14]:
print(y_test)

8    1
1    0
Name: passed, dtype: int64

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
model = LogisticRegression()

In [18]:
model.fit(X_train, y_train)

LogisticRegression()

In [19]:
y_pred = model.predict(X_test)

In [20]:
y_pred

array([1, 0])

In [20]:
y_test

8    1
1    0
Name: passed, dtype: int64

In [21]:
X_test

   hours_studied
8              9
1              2

In [26]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Accuracy in Percentage:", accuracy * 100)

Accuracy: 1.0
Accuracy in Percentage: 100.0

In [39]:
y_prob = model.predict_proba(X_test)

In [40]:
y_prob

array([[0.01799637, 0.98200363],
       [0.98200563, 0.01799437]])